### ISSUE TITLE
on ubuntu getting error on update from 1.3.3 to 1.3.4

### ISSUE THREAD

**Issue by KBYSHanahira** [a3pire/musicard#6] opened 2023-08-29 10:18 UTC
![image](https://github.com/a3pire/musicard/assets/85464400/515a45a4-2770-49a6-ae63-ecb624e6cb71)
![image](https://github.com/a3pire/musicard/assets/85464400/eb0ea7d9-c839-45a7-b3ce-36ead37d1520)
![image](https://github.com/a3pire/musicard/assets/85464400/9779c9d9-3d8f-427d-8cbf-e3096244e7d1)

IDK What happened , but i still work on 1.3.3

**Comment by ZenoXTV** [comment] 2023-08-29 12:34
I also get the same error when I install the module on Windows 10.

**Comment by UnschooledGamer** [comment] 2023-08-29 14:10
> I also get the same error when I install the module on Windows 10.

It is a warning not an error as much as I can see.

**Comment by ZenoXTV** [comment] 2023-08-29 14:24
The problem is that it shows me these errors when I didn't have them before:

```Promise {
  <rejected> TypeError [ReqResourceType]: The resource must be a string, Buffer or a valid file stream.
      at DataResolver.resolveFile (/home/container/node_modules/discord.js/src/util/DataResolver.js:136:11)
      at MessagePayload.resolveFile (/home/container/node_modules/discord.js/src/structures/MessagePayload.js:258:54)
      at /home/container/node_modules/discord.js/src/structures/MessagePayload.js:223:85
      at Array.map (<anonymous>)
      at MessagePayload.resolveFiles (/home/container/node_modules/discord.js/src/structures/MessagePayload.js:223:56)
      at TextChannel.send (/home/container/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:161:50)
      at module.exports.run (/home/container/src/events/poruEvents/player/trackStart.js:92:10)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    code: 'ReqResourceType'
  }
} TypeError [ReqResourceType]: The resource must be a string, Buffer or a valid file stream.
    at DataResolver.resolveFile (/home/container/node_modules/discord.js/src/util/DataResolver.js:136:11)
    at MessagePayload.resolveFile (/home/container/node_modules/discord.js/src/structures/MessagePayload.js:258:54)
    at /home/container/node_modules/discord.js/src/structures/MessagePayload.js:223:85
    at Array.map (<anonymous>)
    at MessagePayload.resolveFiles (/home/container/node_modules/discord.js/src/structures/MessagePayload.js:223:56)
    at TextChannel.send (/home/container/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:161:50)
    at module.exports.run (/home/container/src/events/poruEvents/player/trackStart.js:92:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ReqResourceType'
}
TypeError [ReqResourceType]: The resource must be a string, Buffer or a valid file stream.
    at DataResolver.resolveFile (/home/container/node_modules/discord.js/src/util/DataResolver.js:136:11)
    at MessagePayload.resolveFile (/home/container/node_modules/discord.js/src/structures/MessagePayload.js:258:54)
    at /home/container/node_modules/discord.js/src/structures/MessagePayload.js:223:85
    at Array.map (<anonymous>)
    at MessagePayload.resolveFiles (/home/container/node_modules/discord.js/src/structures/MessagePayload.js:223:56)
    at TextChannel.send (/home/container/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:161:50)
    at module.exports.run (/home/container/src/events/poruEvents/player/trackStart.js:92:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by flam3face** [comment] 2023-08-29 14:27
@KBYSHanahira @ZenoXTV the issue is fixed in **1.3.5**

**Comment by KBYSHanahira** [comment] 2023-08-29 18:26
@flam3face Thank a lot of for update <3
but i have new issue
![musicard](https://github.com/a3pire/musicard/assets/85464400/f685fbea-25f6-43e5-b948-c1823cc24bdb)
the font is square box in version 1.3.5
idk what happend with my font file else or some thing

**Comment by UnschooledGamer** [comment] 2023-08-30 01:41
> @flam3face Thank a lot of for update <3
> but i have new issue
> ![musicard](https://github.com/a3pire/musicard/assets/85464400/f685fbea-25f6-43e5-b948-c1823cc24bdb)
> the font is square box in version 1.3.5
> idk what happend with my font file else or some thing

Probably title has some special characters that the font can't render

**Comment by KBYSHanahira** [comment] 2023-08-30 03:03
i try change font in node_modules/musicard/build/index.js : 
![musicard](https://github.com/a3pire/musicard/assets/85464400/12b44a66-c6c3-44d0-9fbd-fd7a2314d488)

i try in microsoft word to test font : 
![image](https://github.com/a3pire/musicard/assets/85464400/3b4cdb1c-65ae-4b64-a1ae-4be6f2a7cca8)

and on version 1.3.3 font work : 
![image](https://github.com/a3pire/musicard/assets/85464400/e0362655-78c1-4142-8b8c-6d7442d3c8c1)

also i will happy in 1.3.4 can use .webp to show picture work !!!
Cheers to @flam3face ,  you've done well. Thank you for always helping

**Comment by flam3face** [comment] 2023-08-30 03:24
@KBYSHanahira i use same font in all version

**Closed by flam3face** 2023-08-30 03:24 UTC
Labels: bug, fixed
